---
- name: Configure Ubuntu Server
  hosts: all
  become: true
  tasks:
    - import_tasks: tasks/users.yml
    - import_tasks: tasks/packages.yml
    - import_tasks: tasks/grafana.yml
    - import_tasks: tasks/config.yml
