---
- name: Configure Ubuntu Server
  hosts: all
  become: true
  tasks:
    - import_tasks: tasks/user.yml
    - import_tasks: tasks/packages.yml
    - import_tasks: tasks/node_exporter.yml
    - import_tasks: tasks/prometheus.yml
    - import_tasks: tasks/config.yml
