---
- name: Configure Ubuntu Server
  hosts: all
  become: true
  tasks:
    - import_tasks: tasks/users.yml
    - import_tasks: tasks/packages.yml

    - name: Run all tasks under software
      include_tasks: "{{ item }}"
      loop: "{{ lookup('fileglob', 'tasks/software/*.yml') }}"
