---
- name: Configure Ubuntu Server
  hosts: all
  become: true
  tasks:
    - import_tasks: tasks/users.yml
    - import_tasks: tasks/packages.yml

    - name: Include Miniconda installation tasks
      include_tasks: tasks/software/miniconda.yml
      tags: miniconda
