---
- name: Ensure NeoVim is installed
  block:
    - name: Check if NeoVim is installed
      command: nvim --version
      register: nvim_check
      ignore_errors: true

    - name: Include package installation if NeoVim is not installed
      include_tasks: packages.yml
      when: nvim_check.rc != 0
  tags:
    - nvim

- name: Configure NeoVim
  block:
    - name: Clone the configuration repository
      git:
        repo: https://github.com/Henryfzh/linux-setting.git
        dest: /tmp/linux-setting
        version: main  

    - name: Move Neovim configuration to ~/.config/nvim
      copy:
        src: /tmp/linux-setting/nvim/
        dest: ~/.config/nvim/
        remote_src: yes
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Clone lazy.nvim repository if not installed
      git:
        repo: https://github.com/folke/lazy.nvim.git
        dest: ~/.local/share/nvim/lazy/lazy.nvim
        version: stable
  tags:
    - nvim

- name: Configure Tmux
  block:
    - name: Install TPM for tmux
      git:
        repo: https://github.com/tmux-plugins/tpm 
        dest: ~/.tmux/plugins/tpm
        version: master

    - name: Move Tmux configuration to ~/.tmux
      copy:
        src: /tmp/linux-setting/tmux/
        dest: ~/.tmux/
        remote_src: yes
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Move .tmux.conf to home directory
      copy:
        src: /tmp/linux-setting/.tmux.conf
        dest: ~/.tmux.conf
        remote_src: yes
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'
  tags:
    - tmux