---
- name: Download Node Exporter
  shell: |
    wget https://github.com/prometheus/node_exporter/releases/download/v1.6.0/node_exporter-1.6.0.linux-{{ ansible_architecture }}.tar.gz -O /tmp/node_exporter.tar.gz
    tar xvf /tmp/node_exporter.tar.gz -C /tmp
    mv /tmp/node_exporter-*/node_exporter /usr/local/bin/
  args:
    creates: /usr/local/bin/node_exporter

- name: Create Node Exporter systemd service
  copy:
    content: |
      [Unit]
      Description=Node Exporter
      After=network.target

      [Service]
      User=node_exporter
      ExecStart=/usr/local/bin/node_exporter
      Restart=always

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/node_exporter.service
    mode: '0644'

- name: Enable and start Node Exporter
  systemd:
    name: node_exporter
    enabled: true
    state: started
