---
- name: Clone Neovim repository
  git:
    repo: https://github.com/neovim/neovim.git
    dest: /tmp/neovim
    version: stable

- name: Build and install Neovim
  shell: |
    make CMAKE_BUILD_TYPE=Release
    make install
  args:
    chdir: /tmp/neovim
    creates: /usr/local/bin/nvim

- name: Ensure NeoVim is installed
  block:
    - name: Check if NeoVim is installed
      command: nvim --version
      register: nvim_check
      ignore_errors: true

    - name: Include package installation if NeoVim is not installed
      include_tasks: packages.yml
      when: nvim_check.rc != 0
  tags:
    - nvim

- name: Configure NeoVim
  block:
    - name: Clone the configuration repository
      git:
        repo: https://github.com/Henryfzh/linux-setting.git
        dest: /tmp/linux-setting
        version: main  

    - name: Move Neovim configuration to ~/.config/nvim
      copy:
        src: /tmp/linux-setting/nvim/
        dest: ~/.config/nvim/
        remote_src: yes
        owner: "{{ ansible_user_id  }}"
        group: "{{ ansible_user_id  }}"
        mode: '0755'

    - name: Clone lazy.nvim repository if not installed
      git:
        repo: https://github.com/folke/lazy.nvim.git
        dest: ~/.local/share/nvim/lazy/lazy.nvim
        version: stable
  tags:
    - nvim

