---
- name: Install essential packages
  apt:
    name:
      - vim
      - tmux
      - net-tools
      - prometheus
      - npm
      - openssh-server  
      - software-properties-common
    state: present
    update_cache: true

- name: Install Neovim dependencies
  apt:
    name:
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - g++
      - pkg-config
      - unzip
      - curl
      - doxygen
    state: present