---
- name: Install essential packages
  apt:
    name:
      - vim
      - tmux
      - net-tools
      - prometheus
      - npm
    state: present
    update_cache: true

- name: Install Neovim dependencies
  apt:
    name:
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - g++
      - pkg-config
      - unzip
      - curl
      - doxygen
    state: present

- name: Clone Neovim repository
  git:
    repo: https://github.com/neovim/neovim.git
    dest: /tmp/neovim
    version: stable

- name: Build and install Neovim
  shell: |
    make CMAKE_BUILD_TYPE=Release
    make install
  args:
    chdir: /tmp/neovim
    creates: /usr/local/bin/nvim

- name: Install prerequisites for Grafana
  apt:
    name:
      - apt-transport-https
      - software-properties-common
      - wget
    state: present

- name: Add Grafana GPG key
  shell: |
    wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor | tee /etc/apt/keyrings/grafana.gpg > /dev/null
  args:
    creates: /etc/apt/keyrings/grafana.gpg

- name: Add Grafana APT repository
  copy:
    content: "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main\n"
    dest: /etc/apt/sources.list.d/grafana.list
    owner: root
    group: root
    mode: '0644'

- name: Update APT cache
  apt:
    update_cache: true

- name: Install Grafana
  apt:
    name: grafana
    state: present

- name: Enable and start Grafana service
  systemd:
    name: grafana-server
    enabled: true
    state: started
