---
- name: Install essential packages
  apt:
    name:
      - vim
      - tmux
      - net-tools
      - prometheus
      - npm
      - openssh-server  
      - software-properties-common
    state: present
    update_cache: true

- name: Install Neovim dependencies
  apt:
    name:
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - g++
      - pkg-config
      - unzip
      - curl
      - doxygen
    state: present

- name: Clone Neovim repository
  git:
    repo: https://github.com/neovim/neovim.git
    dest: /tmp/neovim
    version: stable

- name: Build and install Neovim
  shell: |
    make CMAKE_BUILD_TYPE=Release
    make install
  args:
    chdir: /tmp/neovim
    creates: /usr/local/bin/nvim